#!/usr/bin/env bash

set -eo pipefail

source terraform.tfvars

terraform remote config \
    -backend="s3" \
    -backend-config="bucket=$s3_bucket" \
    -backend-config="key=terraform.tfstate" \
    -backend-config="region=$aws_region"
