#!/usr/bin/env bash

set -eo pipefail

if [ "$1" == "-h" ]; then
    echo "Symlinks scripts from the current directory into /usr/local/bin/"
    echo "Must be executed as root"
    exit 0
fi

for file in metaconfig findup; do
    ln --symbolic --force $PWD/$file /usr/local/bin/$file
done
