#!/usr/bin/env python
"""
Usage: spp SWAGGER_TEMPLATE [options]

Arguments:
    SWAGGER_TEMPLATE    swagger template file
    
Options:
    -h --help           show this help message

spp is a swagger preprocessor. Uses Jinja2 syntax.

Files
spp looks for files in the current directory.
SWAGGER_TEMPLATE        the template to be processed
.variables              the variables file with key=value pairs
Files referenced from the SWAGGER_TEMPLATE are converted into json strings.
"""

from __future__ import print_function

import docopt
import jinja2
import json


def main(args):
    env = jinja2.Environment(loader=jinja2.FunctionLoader(load_template), undefined=jinja2.runtime.StrictUndefined)
    template = env.get_template(_main_file_name)
    variables = load_variables(".variables")
    
    print(template.render(variables))


def load_template(name):
    with open(name) as f:
        template_content = f.read()

    # don't jsonify main template
    if name != _main_file_name:
        template_content = to_json_string(template_content)
    
    return template_content
        
        
def to_json_string(s):
    # convert into a json string and unqote the result
    return json.dumps(s)[1:-1]


def load_variables(file_name):
    variables = {}
    with open(file_name) as f:
        for line in f:
           (key, val) = line.split("=")
           variables[key.strip()] = val.strip()
    return variables


args = docopt.docopt(__doc__, version="1.0")
_main_file_name = args.get("SWAGGER_TEMPLATE")

if __name__ == '__main__':
    main(args)
